### ISSUE TITLE
Ativar visualizar xml sem soap ou com Soap no log

### ISSUE THREAD

**Issue by resplandes** [Samuel-Oliveira/Java_CTe#10]
Seria interessante se fosse possível uma configuração para habilitar a visualização do SOAP gerado para caso de testes na API assim a pessoa possa decidir se quer ver o xml gerado sem o empacotamento ou não.

**Comment by Samuel-Oliveira** [comment]
O Soap, é gerado em tempo de envio, então não é possivel capturar ele de forma dinamica.
Mas caso precise do SOAP só ativa o DEBUG para Http que vai mostrar.
