### ISSUE TITLE
DOM e esta SDK versão 6.

### ISSUE THREAD

**Issue by Nicholas-Barbosa** [Samuel-Oliveira/Java_CTe#14]
Você esta usando alguma biblioteca como xml apis na versão 6?Esta dando conflito com a biblioteca DOM.No java 9 e superior,não pode haver o mesmo pacote, em dois módulos diferentes,pois quebra o requisito de visibilidade única.

**Comment by Samuel-Oliveira** [comment]
Beleza? Diretamente não, mas pode ocorrer em alguma subdependencia,
Recomendo nesse caso fazer um exclude dela.
