### ISSUE TITLE
Configuração contigencia SVC

### ISSUE THREAD

**Issue by VictorJunior** [Samuel-Oliveira/Java_CTe#15]
Criar o método setContigenciaSVC, assim como existe na API NFe para configuração de entrada em contingência.

**Comment by Samuel-Oliveira** [comment]
Beleza, Adicionado pra proxima Demanda!

**Comment by jardelnovaes** [comment]
@Samuel-Oliveira, para essa atividade tem alguém que poderia "testar" em Homologação?
Não tenho certificado/acesso para emissão de CT-e.

Removi o plugin maven-surefire-plugin, ele estava apontando para um recurso que não existe no CT-e e estava conflitando com o Unit Test que fiz.

**Comment by Samuel-Oliveira** [comment]
Antes de gerar versão vou efetuar os testes. Obrigado
