### ISSUE TITLE
Falha no esquema xml

### ISSUE THREAD

**Issue by belemlc** [Samuel-Oliveira/Java_CTe#18]
Fala ae Samuel, eu vi que já teve uma issue com esse problema, mas não teve resposta, gostaria de saber se é um problema dos dados que estou enviando, pq toda vez retorna esse erro.

Status:215
Motivo:Rejeicao: Falha no esquema xml

**Comment by robertodpassos** [comment]
Boa tarde!
Geralmente sim, é uma falha nos dados informados.

É possível validar o XML neste link https://dfe-portal.svrs.rs.gov.br/NFE/ValidadorXml

Ou entra na no Discord https://discord.gg/ZXpqnaV. Assim podemos analisar melhor esta situação.

Abraço!

**Comment by belemlc** [comment]
Boa, vou entrar sim no canal, valeu pela ajuda @robertodpassos ;)

**Comment by robertodpassos** [comment]
Blz, acabei pegando o link errado. Para CTe é este 
https://dfe-portal.svrs.rs.gov.br/CTE/ValidadorXML

**Comment by belemlc** [comment]
Boa, vou dar uma olhada agora, value mesmo.

**Comment by belemlc** [comment]
Então @robertodpassos, em ambos validadores eu estou recebendo esse erro, sabe dizer o que pode ser?

PARSER XML: | OK
-- | --
TIPO DE MENSAGEM: | Tipo de Schema não tratado: distDFeInt

**Comment by robertodpassos** [comment]
A sim, mas tu não esta querendo enviar o CT-e. Tu queres consultar no ambiente nacional, é isso?

**Comment by belemlc** [comment]
Sim, isso mesmo.
