### ISSUE TITLE
Lançar versão com axiom-api na versão 1.3.0

### ISSUE THREAD

**Issue by filipegarrett** [Samuel-Oliveira/Java_CTe#20]
Boa tarde;

A dúvida/problema tem solução no seguinte: atualizar o projeto para usar a versão 1.3.0 da biblioteca axiom-api.

Eu estou encontrando alguns problemas ao tentar rodar a biblioteca com Java 11. Ocorre um erro de duplicidade de módulos porque a lib Jaxen 1.6.0, que é uma dependência de Axiom-Api, carrega org.w3c, duplicando essas classes. A versão 1.3.0 da axiom-api carrega o jaxen mais recente, eliminando o problema.

**Comment by Samuel-Oliveira** [comment]
A troca de Bibliotecas irá influenciar varios sistemas q ja estao implementados nessa versão. 
Nesse momento ela não é viavel.
