### ISSUE TITLE
URLs de Webservice

### ISSUE THREAD

**Issue by andrade-felipe-dev** [Samuel-Oliveira/Java_CTe#23]
Boa tarde.

Por gentileza verificar a lista de urls de webservices que se encontram presentes neste arquivo https://github.com/Samuel-Oliveira/Java_CTe/blob/master/src/main/resources/WebServicesCte.ini  , há algumas urls que estão incorretas.
Ex: qrcode do estado de MG.
Como está no seu arquivo: QR_Code=https://hcte.fazenda.mg.gov.br/portalcte/sistema/qrcode.xhtml
Como está no portal do DF-e: https://cte.fazenda.mg.gov.br/portalcte/sistema/qrcode.xhtml

Segue o link dos webservices disponíveis por estado.
https://dfe-portal.svrs.rs.gov.br/Cte/Servicos

**Comment by Samuel-Oliveira** [comment]
Oks. Vou fazer as modificações para próxima versão.

**Comment by Samuel-Oliveira** [comment]
Corrigido versão na versão 3.00.9
