### ISSUE TITLE
Versão 4.00

### ISSUE THREAD

**Issue by leonardorocha96** [Samuel-Oliveira/Java_CTe#26]
Boa noite,

A versão 4.00 está disponível na versão 3.00.10?

**Comment by Samuel-Oliveira** [comment]
Ainda não fiz. 
Está na agenda para esse mês.

**Comment by leonardorocha96** [comment]
Beleza Samuel. Fiz uns testes e consegui baixar pela DistribuiçãoCte os cte's do modelo 4.00, e a biblioteca reconhece os mesmos para interpretação dos dados nas classes Java.

Obrigado!
