### ISSUE TITLE
br.com.swconsultoria.cte.schema_400.enviCTe.TCTe cannot be resolved

### ISSUE THREAD

**Issue by muriloht** [Samuel-Oliveira/Java_CTe#27]
Estou tentando atualizar um projeto que usava a versão 3.00.7 para a versão 4.00.2 

Após atualizar a dependencia do maven, a classe (entre outras)  br.com.swconsultoria.cte.schema_400.enviCTe.TCTe não pode ser resolvida:

![image](https://github.com/Samuel-Oliveira/Java_CTe/assets/5605206/ff540b81-f374-40e4-85df-133587cadf7b)

Verificando na documentação o tipo deveria existir: 

![image](https://github.com/Samuel-Oliveira/Java_CTe/assets/5605206/a17cebf2-d4c6-4617-8253-8afa84c4f6ee)

Mas checando na árvore do projeto realmente não existe o pacote enviCte e outros que estão apresentando erro.

Ainda não olhei à fundo manuais, etc da nova versão, mas a dúvida que fiquei é se o projeto ainda está sendo atualizado para a versão 4.00 do CTe, ou somente a documentação que ainda não foi atualizada?

**Comment by wictormk** [comment]
Olá, boa tarde!
Aqui consegui efetuar a atualização já para a versão 4.0 do CTe.
Alguns objetos tiveram suas estruturas e caminhos alterados mesmo, no seu caso acredito que resolveria parte do problema atualizando a referencia de `br.com.swconsultoria.cte.schema_300.enviCTe.TCTe` para `br.com.swconsultoria.cte.schema_400.cte.TCTe`.

**Comment by wictormk** [comment]
https://github.com/Samuel-Oliveira/Java_CTe/tree/master/src/test/java/br/com/swconsultoria/cte aqui você consegue encontrar alguns casos de uso para usar como exemplo. Ainda falta alguma coisinha ou outra, mas acho que consiga prosseguir tranquilamente.

**Comment by muriloht** [comment]
Opa, tá jóia @wictormk ... eu até cheguei a ver o tipo br.com.swconsultoria.cte.schema_400.cte.TCTe mas como na doc estava ainda o enviCTe perguntei antes de seguir.

vou ajustar por aqui então, obrigado!
