### ISSUE TITLE
Download Maven versão 3.00.2

### ISSUE THREAD

**Issue by fredwilliamtjr** [Samuel-Oliveira/Java_CTe#3]
Caro Samuel, não esta sendo possível baixar via Maven a versão **3.00.2**, esta apresentando a seguinte mensagem!

Failed to execute goal on project SmartXmlGateway: Could not resolve dependencies for project br.com.fwtj:Teste:war:v1: Failure to find br.com.samuelweb:java-cte:jar:3.00.2 in http://www.autocomsistemas.com.br:8081/nexus/content/repositories/autocom/ was cached in the local repository, resolution will not be reattempted until the update interval of Snapshot has elapsed or updates are forced -> [Help 1]

**A versão 3.00.1 esta baixando sem nenhum problema!**

**Obrigado!**

**Comment by Samuel-Oliveira** [comment]
Tudo Bem? Isso parece ser um Bug com o Maven Vs Nexus.
Me adicione no Skype (samuk.exe@hotmail.com) que eu te ajudo a resolver!

**Comment by Samuel-Oliveira** [comment]
Resolvido!
