### ISSUE TITLE
Evento 110180

### ISSUE THREAD

**Issue by DanilojSousa** [Samuel-Oliveira/Java_CTe#36]
Boa tarde, Samuel.

Verifiquei no projeto e percebi que existe a classe ComprovanteEntrega, no entanto, o método associado está recebendo a classe TEvento. O problema é que essa classe TEvento não contém os mesmos parâmetros descritos na documentação, como hashEntrega, dhEntrega, entre outros. Esse serviço específico não está implementado no projeto? Não encontrei nenhuma classe que contemple esses valores, mas fiquei com dúvida por conta da presença da classe ComprovanteEntrega

**Comment by Samuel-Oliveira** [comment]
Blz? A biblioteca já possui todos os Eventos.
O TEvento é uma classe generia que serve para todos os eventos, o que vc deve fazer é preencher o Objeto do Comprovante de Entrega (br.com.swconsultoria.cte.schema_300.evCECTe) e adicionar ao TEvento.
Siga o exemplo doi cancelamento: https://github.com/Samuel-Oliveira/Java_CTe/wiki/Cancelamento-Cte

**Comment by DanilojSousa** [comment]
Encontrei, muito obrigado pelo retorno.
