### ISSUE TITLE
Connection reset ao consumir serviços de homologação na Uf MT

### ISSUE THREAD

**Issue by resplandes** [Samuel-Oliveira/Java_CTe#8]
Boa tarde @Samuel-Oliveira estou consumindo serviços de homologação na uf de mt e a api de cte retorna um erro Connection reset, porem testo de outra aplicação que não usa a api e o serviço está ativo, consulto a disponibilidade e também está em operação.
`Api Java Cte Versão 3.00.5 - Samuel Olivera - samuel@swconsultoria.com.br
Certificado: ARQUIVO_BYTES - MATIAS E MATIAS LTDA:10658657000102 - Vencimento: 2020-05-01
Ambiente: Homologação - Estado: Mato Grosso - Versão: 3.00
Versão Cte: 3.00 - WebService: https://homologacao.sefaz.mt.gov.br/ctews/services/CteStatusServico
Erro:Connection reset`
Lembrando que isso ocorre somente com os serviços em homologação.
**Já testei em ambientes diferentes com maquinas e internet diferente**

![unife_cte](https://user-images.githubusercontent.com/3025776/62826069-56083880-bb83-11e9-9ebf-4b72a94f30cf.png)

**Comment by LeonardoWiest** [comment]
Prezados, estou com o mesmo problema. Aparentemente acredito que seja algo referente ao protocolo de comunicação (TLS 1.2) com a SEFAZ do MT. O erro ocorre no momento em que é feita a tentativa de abertura de conexão com WS, utilizando o Axis2. Para mim ocorre na emissão de NFC-e e em alguns casos na consulta de status.

**Comment by Samuel-Oliveira** [comment]
Corrigido!
