### ISSUE TITLE
Retorno de Evento Vazio

### ISSUE THREAD

**Issue by resplandes** [Samuel-Oliveira/Java_CTe#9]
@Samuel-Oliveira estou enviando eventos de cancelamento e carta de corração e estou recebendo um retorno null pode validar o que está havendo.
O XML de envio está otimo pois usei ele para enviar pelo UniNFe e foi enviado normalmente.
**Retorno**
`Api Java Cte Versão 3.00.5 - Samuel Olivera - samuel@swconsultoria.com.br
Certificado: ARQUIVO_BYTES - {659A4504-BEA4-4898-B3C0-B11F9E6DBC96} - Vencimento: 2020-05-01
Ambiente: Produção - Estado: Mato Grosso - Versão: 3.00
Gravando xml da NFe
Xml Evento: <?xml version="1.0" encoding="UTF-8"?><eventoCTe xmlns="http://www.portalfiscal.inf.br/cte" versao="3.00"><infEvento Id="ID1101115119081065865700010257001000000012101983918101"><cOrgao>51</cOrgao><tpAmb>1</tpAmb><CNPJ>10658657000102</CNPJ><chCTe>51190810658657000102570010000000121019839181</chCTe><dhEvento>2019-08-12T08:01:53-03:00</dhEvento><tpEvento>110111</tpEvento><nSeqEvento>1</nSeqEvento><detEvento versaoEvento="3.00"><evCancCTe><descEvento>Cancelamento</descEvento><nProt>151190304103324</nProt><xJust>51190510658657000102550010000097061121296020</xJust></evCancCTe></detEvento></infEvento><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><Reference URI="#ID1101115119081065865700010257001000000012101983918101"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><DigestValue>gOJtWX2oTziDnL7zmhbmCkOnUSU=</DigestValue></Reference></SignedInfo</eventoCTe>
Versão Cte: 3.00 - WebService: https://cte.sefaz.mt.gov.br/ctews2/services/CteRecepcaoEvento
Gravando xml da NFe
java.lang.NullPointerException`

**XML criado pela API e enviado pelo UniNFe**
![xml_gerado_pela_api](https://user-images.githubusercontent.com/3025776/62866987-333f6680-bce0-11e9-9760-e5fda17411b7.jpg)
**XML Retornado pelo UniNFe apos enviar o XML gerado pela API**
![xml_gerado_pela_api](https://user-images.githubusercontent.com/3025776/62867012-3e929200-bce0-11e9-98bb-f847d34433c4.jpg)
**XML Gerado de Retorno apos envio pela API**
![xml_retorno_api](https://user-images.githubusercontent.com/3025776/62867065-5c5ff700-bce0-11e9-8b90-397858cc72d2.jpg)

**Comment by resplandes** [comment]
**Bom dia, consegui solucionar o problema com a seguinte mudança, na classe CteRecepcaoEventoStub no método statico CteCabecMsgE ao criar a constante MY_QNAME ele recebe alguns paramentros dentre eles uma String "n1" eu deixei vazio esse valor pois ele influencia na formação da tag <versaoDados> deixando ela da seguinte forma <n1:versaoDados> e o serviço de Cte do MT não conseguia identificar ela, assim então revendo esse valor foi resolvido para os eventos de cancelamento de CTe e CCe de Cte**
**### Antes**

![problema](https://user-images.githubusercontent.com/3025776/62938963-2123fd80-bd9e-11e9-8c05-f07e858a81d9.jpg)

**### Depois**

![solucao](https://user-images.githubusercontent.com/3025776/62939030-487aca80-bd9e-11e9-99eb-b801bcd3b557.jpg)

**Comment by resplandes** [comment]
Problema continua na versão atual

**Comment by viniciussousa** [comment]
Eu consegui resolvendo conforme o mencionado, porém eu havia colocado a lib como dependência do projeto, porém agora terei que pegar os códigos e baixar.

**Comment by Samuel-Oliveira** [comment]
Resolvido!
